### ISSUE TITLE
Missing @types/node-app-store-connect-api 

### ISSUE THREAD

**Issue by envative-mobile-team** [dfabulich/node-app-store-connect-api#1]
I have not been able to find a `@types/node-app-store-connect-api` package which I need to use in my typescript cli app

**Comment by dfabulich** [comment]
You're right, there isn't one. But I don't think you're supposed to need one!

My understanding is that a TS app should be able to just consume the JS version directly. I created a test repository using TypeScript, and I was able to use `node-app-store-connect-api` directly without errors.

https://github.com/dfabulich/node-app-store-connect-typescript-test

Now, having said that, I'd be happy to review a PR to add a `.d.ts`, or you can file a PR on https://github.com/DefinitelyTyped/DefinitelyTyped

But I think the `.d.ts` file would be _really_ basic. `read` will return a promise for `data`, but `data` would be `any`. (Remember, some requests return arrays, and some return a single object.) `create` will accept a `type: string`, `attributes: any`, and `relationships: any | undefined`. It really wouldn't help you catch any bugs, or to autocomplete anything useful.

It would be even fancier to use Apple's OpenAPI specification https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip to generate types for arguments and results.

But I think it could be a huge hassle to generate types that way; at a minimum, it would do something _very_ fancy with string parsing and the `infer` keyword, following a guide like this: https://lihautan.com/extract-parameters-type-from-string-literal-types-with-typescript/ 

Soooo a fully TS-aware version of this library might do something else entirely, like converting the `read` and `readAll` functions to not take URLs, but just take an object type and a `params` object that gets transformed into an URL. So you could `await read('apps', { params: { limit: 1 } } )` and then aggressively use string-literal types and the OpenAPI specification to generate heavily overloaded type parameters for all of the API functions.

That sounds _so_ complicated that I think it might make sense to do _that_ as a separate repository or something, but, again, I'm open to accepting PRs if someone really wants to take that on.

**Comment by dfabulich** [comment]
I got curious and investigated further. https://github.com/acacode/swagger-typescript-api seemed like it would probably do the trick, but in order to do stuff like automatic retries, crawling all pages, converting the inclusions array into a tree (as a type-safe tree?!), and allowing you to pass in full objects as relationships (instead of manually trimming them down to a `data` object), it would require a _lot_ of work. Wayyy more work is required for that than I'm prepared to do.

The alternative is still to write my own generator by hand. I'm … not gonna do that, either.
