### ISSUE TITLE
'index.mjs' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by chbeer** [dfabulich/node-app-store-connect-api#3]
When trying to import node-app-store-connect-api into my project I get:

error TS7016: Could not find a declaration file for module 'node-app-store-connect-api'. '…/node_modules/node-app-store-connect-api/index.mjs' implicitly has an 'any' type.

**Comment by dfabulich** [comment]
This was filed as issue #1 but I'm not able to reproduce it.

https://github.com/dfabulich/node-app-store-connect-api/issues/1#issuecomment-1221004744

> My understanding is that a TS app should be able to just consume the JS version directly. I created a test repository using TypeScript, and I was able to use `node-app-store-connect-api` directly without errors.
>
> https://github.com/dfabulich/node-app-store-connect-typescript-test

I assume that my example repo will be sufficient for your needs. If not, feel free to reply with steps to reproduce (ideally push a sample repository to Github) and I'll take a look.
